version: '2'

services:
  nginx:
    extends:
      file: dev-share.yml
      service: nginx
    links:
      - php
    volumes:
      - ${NGINX_PROJECT}:/etc/www/project
      - ${NGINX_CONFIG}:/etc/nginx/nginx.conf
      - ${NGINX_PROJECT_CONFIG}:/etc/nginx/conf.d/project_conf

  php:
    extends:
      file: dev-share.yml
      service: php
    volumes:
      - ./project/php_project/:/etc/www/project/php_project
    links:
      - mysql

  mysql:
    extends:
      file: dev-share.yml
      service: mysql

  phpmyadmin:
    extends:
      file: dev-share.yml
      service: phpmyadmin
    links:
      - mysql:db
